# Ylearn Casual Discovery - Synthetic Data

In [3]:
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath('./introduction.ipynb'))))

In [5]:
import pandas as pd

from ylearn.exp_dataset.gen import gen
from ylearn.causal_discovery import CausalDiscovery, GolemDiscovery, DagmaDiscovery

## 1. Synthetic data

In [6]:
X = gen()

X = pd.DataFrame(X, columns=[f'x{i}' for i in range(X.shape[1])])

## 2. Notears

See (https://arxiv.org/pdf/1803.01422.pdf) for reference.

In [8]:
cd = CausalDiscovery(hidden_layer_dim=[3])
est = cd(X, threshold=0.01, return_dict=True)
print(est)

08-17 12:04:33 I ylearn.c._discovery.py 202 - learning data(100, 5) with device=cpu, dtype=torch.float64, dims=[5, 3, 1]
08-17 12:04:53 I ylearn.c._discovery.py 226 - trim causal matrix to DAG, threshold=0.01.
(OrderedDict([(0, []), (1, []), (2, [0]), (3, [0, 1, 2]), (4, [0, 1, 2, 3])]), array([[0.        , 0.        , 0.02899442, 0.20158441, 0.18061451],
       [0.        , 0.        , 0.        , 0.25362264, 0.06218096],
       [0.        , 0.        , 0.        , 0.04275383, 0.41436427],
       [0.        , 0.        , 0.        , 0.        , 0.36565398],
       [0.        , 0.        , 0.        , 0.        , 0.        ]]))


## 3. Golem

See (https://arxiv.org/pdf/2006.10201.pdf) for reference.

In [13]:
gocd = GolemDiscovery()

est_go_dict, est_go = gocd(X, threshold=0.3, return_dict=True)
print(est_go_dict)
print(est_go)

08-17 12:08:15 I ylearn.c._discovery.py 363 - learning data(100, 5) with device=cpu, dtype=torch.float64, dims=[5, 100]
08-17 12:08:27 I ylearn.c._discovery.py 382 - trim causal matrix to DAG, threshold=0.3.
OrderedDict([(0, [1, 3]), (1, []), (2, [1]), (3, []), (4, [])])
[[0.         0.         0.         0.         0.        ]
 [0.3279995  0.         0.31600001 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.34809389 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


## 4. DAGMA

See (https://arxiv.org/pdf/2209.08037.pdf) for reference.

In [12]:
dagmacd = DagmaDiscovery()
est_dagma_dict, est_dagma = dagmacd(X, threshold=0.3, return_dict=True)
print(est_dagma_dict)
print(est_dagma)

08-17 12:07:57 I ylearn.c._discovery.py 563 - learning data(100, 5) with device=cpu, dtype=torch.float64, dims=[5, 100]
08-17 12:08:01 I ylearn.c._discovery.py 573 - trim causal matrix to DAG, threshold=0.3.
OrderedDict([(0, []), (1, []), (2, []), (3, [0, 1]), (4, [0, 1, 2, 3])])
[[ 0.          0.          0.          0.61648153  0.        ]
 [ 0.          0.          0.         -0.80596209 -1.29988211]
 [ 0.          0.          0.          0.         -1.53210485]
 [ 0.          0.          0.          0.         -1.43863579]
 [ 0.          0.          0.          0.          0.        ]]
