In [1]:
import torch

import pandas as pd
import numpy as np
import torch.nn as nn

In [37]:
ab

array([[1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 1.]])

In [32]:
e = np.array([['hello', 'bad'], ['good', 'bad'], ['hey', 'not'], ['ok', 'not'
]])

In [34]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
c = OneHotEncoder()
c.fit(e)
c.transform(e).toarray()

array([[0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1.]])

In [42]:
f = OrdinalEncoder()
f.fit_transform(e)
f.categories_

[array(['good', 'hello', 'hey', 'ok'], dtype='<U5'),
 array(['bad', 'not'], dtype='<U5')]

In [60]:
from itertools import product
list(product([np.array([0, 1, 2, 3]), np.array([0, 1]), np.array([0, 1])]))

[(array([0, 1, 2, 3]),), (array([0, 1]),), (array([0, 1]),)]

In [56]:
from sklearn.linear_model import LinearRegression
l = LinearRegression()
x = np.array([[1], [2], [3], [4]])
y = (np.random.normal() * (x)).ravel()
l.fit(x, y)

LinearRegression()

In [19]:
np.all(np.array([[1, 2, 3], [4, 5, 6]]) == np.array([1, 2, 3]), axis=1)

array([ True, False])

In [29]:
a = np.ones((3, 2, 4))
a[:, :, 1] = np.zeros((3, 2))

In [41]:
np.ones((3, 2)).squeeze()

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
def broadcast_unit_treatments(X, d_t):
    """
    Generate `d_t` unit treatments for each row of `X`.
    Parameters
    ----------
    d_t: int
        Number of treatments
    X : array
        Features
    Returns
    -------
    X, T : (array, array)
        The updated `X` array (with each row repeated `d_t` times),
        and the generated `T` array
    """
    d_x = X.shape[0]
    eye = np.eye(d_t)
    # tile T and repeat X along axis 0 (so that the duplicated rows of X remain consecutive)
    T = np.tile(eye, (d_x, 1))
    Xs = np.repeat(X, d_t, axis=0)
    return Xs, T
broadcast_unit_treatments(np.random.randint(0, 3, (3, 2)), 3)

(array([[0, 1],
        [0, 1],
        [0, 1],
        [2, 1],
        [2, 1],
        [2, 1],
        [2, 0],
        [2, 0],
        [2, 0]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [56]:
a = [1, 2, 3]
a.insert(0, 0)
np.ones((5,1)).repeat(3, axis=1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
a = np.zeros((1, 5))
a[:, 0] = 1
np.repeat(a, 2, axis=0)

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]])[np.array([True, False])]

In [45]:
np.ones((5, 4)).reshape((-1, 3, ) + 2)

TypeError: can only concatenate tuple (not "int") to tuple

In [64]:
a = ([0, 1], [0, 1, 2], [0, 1, 2, 3], [0,1])
from estimator_model.utils import cartesian
cartesian((np.array([1, 2, 3]), np.array([4, 5, 6])))
c = [np.array([2, 3, 4]), np.array([4, 5, 5])]
b = (np.arange(len(i)) for i in c)
cartesian(b)

TypeError: object of type 'generator' has no len()

In [61]:
len(np.array([2, 3, 4]))

3

In [ ]:
product()

In [3]:
np.array([[1, 2, 3], [4, 5,5]]).ravel()

array([1, 2, 3, 4, 5, 5])

In [6]:
np.eye(5, 3)[np.array([1, 2, 2, 1, 1])]

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [98]:
a = np.array([['good', 'hello'], ['bad', 'hello'], ['good', 'not']])
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
o = OneHotEncoder()
o.fit(np.array([1, 1, 0, 1]).reshape(-1, 1))
o.categories_

[array([0, 1])]

In [4]:
np.array([np.ones(2,), np.ones(2, ), np.ones(2, )])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
list([1, 2, 3])

[1, 2, 3]

In [8]:
np.repeat(np.array([[4, 5, 6]]), 3, axis=0)

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [2]:
from estimator_model.utils import get_group_ids
target = np.repeat(np.array([[4, 5, 6]]), 3, axis=0)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 3, 4], [3, 4, 5], [1, 1, 1]])
get_group_ids(target, a, a, b)

[array([[4, 5, 6]]), array([[3, 4, 5]])]

In [ ]:
np.mean()

In [ ]:
np.concatenate()

In [113]:
index = np.all(np.array([[1, 2, 3], [1, 0, 1]]) == np.array([[1, 0, 3], [1, 0, 1]]), axis=1)
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])[np.where(index)]

array([[4, 5, 6]])

In [94]:
np.argmax(np.random.normal(size=((3, 2))), axis=1)

array([1, 1, 1])

In [92]:
np.concatenate((np.ones((3, 1)), np.random.normal(size=((3, 2))), np.zeros((3, 1))), axis=1)

array([[ 1.        ,  0.19681735, -1.1459864 ,  0.        ],
       [ 1.        ,  1.92138143,  0.37209335,  0.        ],
       [ 1.        , -0.80434229,  0.55304074,  0.        ]])

In [15]:
np.zeros)

In [64]:
torch.argmax(
    nn.Softmax(dim=1)(torch.randn(5, 3))
, dim=1).reshape(-1, 1)

tensor([[2],
        [0],
        [1],
        [1],
        [1]])

In [71]:
a = nn.Softmax(dim=1)
b = nn.LogSoftmax(dim=1)
c = torch.randn(5, 3)
torch.log(a(c))
nn.CrossEntropyLoss

tensor([[-0.1901, -2.6149, -2.3034],
        [-1.4519, -0.8391, -1.0973],
        [-0.9513, -0.8132, -1.7701],
        [-3.6564, -2.8858, -0.0852],
        [-1.4684, -0.3985, -2.3190]])

In [74]:
b(c)

tensor([[-0.1901, -2.6149, -2.3034],
        [-1.4519, -0.8391, -1.0973],
        [-0.9513, -0.8132, -1.7701],
        [-3.6564, -2.8858, -0.0852],
        [-1.4684, -0.3985, -2.3190]])

In [34]:
a = torch.cat((torch.ones(5, 3), torch.zeros(5, 2)), dim=1)
torch.cat((a[:, :5], a[:, 5:5]), dim=1)

tensor([[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]])

In [35]:
m = nn.Embedding(5, 4)
m(torch.tensor([1, 2, 3, 4,2]))

tensor([[ 0.9123, -0.3915,  0.1124,  0.3993],
        [ 2.1194,  0.1742, -0.6385,  0.0089],
        [ 0.0088, -0.6977, -0.4991,  1.0913],
        [ 0.3151, -0.0975, -0.6318, -0.1264],
        [ 2.1194,  0.1742, -0.6385,  0.0089]], grad_fn=<EmbeddingBackward0>)

In [52]:
torch.argmax(torch.eye(5, 4), dim=0).reshape(-1, 1)

tensor([[0],
        [1],
        [2],
        [3]])

In [57]:
m = nn.Softmax(dim=1)
m(torch.randn(5, 3))

tensor([[0.1918, 0.3555, 0.4527],
        [0.1439, 0.4630, 0.3932],
        [0.8279, 0.1352, 0.0369],
        [0.1293, 0.3380, 0.5327],
        [0.1388, 0.7279, 0.1333]])

In [43]:
torch.where(torch.eye(5, 4).index_select(dim=0, index=(torch.ones(5,) * 2).int()) == 1)

tensor([2, 2, 2, 2, 2])

In [19]:
torch.zeros(5,).mean(dim=0)

tensor(0.)

In [12]:
pd.DataFrame({'a':['hello', 'good', 2]}).values

array([['hello'],
       ['good'],
       [2]], dtype=object)

In [9]:
a = np.array([1, 2, 3, 3, 1])
torch.tensor(a).shape

torch.Size([5])

In [73]:
a = np.random.randn(3, 4)
a

array([[ 0.3866119 ,  0.53135121,  1.57163397, -0.05024657],
       [-1.15621478,  0.51949391,  0.46480889,  0.3432628 ],
       [-1.13285389, -0.21865636,  0.2157348 , -0.33427615]])

In [77]:
for i, j in enumerate(a.T):
    a = j


array([-0.05024657,  0.3432628 , -0.33427615])

In [38]:
a = np.random.randn(3, 5)
a.argmax(axis=1)

array([4, 4, 4])

In [54]:
w = [
        np.random.normal(size=(4, 1)) for i in range(3)
    ]
w = np.concatenate(tuple(w), axis=1)
w_coef = np.random.normal(
    1, 0.2, size=(2, 3)
)
x = w.dot(w_coef.transpose())

In [64]:
np.dot(np.random.randn(3,).transpose(), np.random.randn(3, 2)).transpose()

array([4.07799799, 0.88329315])

In [60]:
np.eye(2)[x.argmax(axis=1)]

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [46]:
x

array([[-1.85906821, -1.32622782, -1.19364618, -1.53628564],
       [-1.81711645, -1.8115858 , -1.55145149, -1.7550974 ],
       [-0.85039268, -0.28857254, -0.35973296, -0.64413723],
       [-1.45962002, -1.51957314, -1.2924692 , -1.43797645]])

In [24]:
nn.Softmax(dim=1)(a).argmax(dim=1).view(3, -1)

tensor([[0],
        [0],
        [0]])

In [9]:
a.transpose().shape

(4, 3)

In [79]:
a = torch.randn(3, 2)
b = torch.randn(3, 2)
torch.sum(a * b, dim=1).unsqueeze(1).shape

torch.Size([3, 1])

In [298]:
pi = torch.randn(3, 2)
pi_ = torch.exp(pi)
pi_

tensor([[0.8265, 0.9079],
        [0.5721, 5.1133],
        [2.0180, 0.2811]])

In [302]:
pi_ = pi_ / torch.sum(pi_, dim=1).unsqueeze(1).expand_as(pi_)
pi_

tensor([[0.4765, 0.5235],
        [0.1006, 0.8994],
        [0.8777, 0.1223]])

In [303]:
mu = torch.randn(3, 2, 3)
sigma = torch.abs(torch.randn(3, 2, 3))

In [305]:
mix = torch.distributions.Categorical(pi_)
comp = torch.distributions.Independent(torch.distributions.Normal(mu, sigma), 1)
gmm = torch.distributions.MixtureSameFamily(mix, comp)

In [329]:
d = gmm.sample()
d

tensor([[ 0.1713, -1.5641, -0.1730],
        [-2.0129,  0.8305, -1.4073],
        [-0.1666, -0.4928,  0.3084]])

In [330]:
d.view(-1, 3)

tensor([[ 0.1713, -1.5641, -0.1730],
        [-2.0129,  0.8305, -1.4073],
        [-0.1666, -0.4928,  0.3084]])

In [109]:
a = torch.tensor([1, 2, 3, 4])
b = torch.zeros((4, 4))
torch.eye(4, 4)[1]

tensor([0., 1., 0., 0.])

In [169]:
f = torch.rand(3, 1)

In [170]:
g = f.clone().detach()
g

tensor([[0.6147],
        [0.0253],
        [0.5778]])

In [171]:

for i in range(5):
    f = torch.rand(3, 1)
    g = torch.concat((f, g), dim=0)
g


tensor([[0.1551],
        [0.1150],
        [0.5389],
        [0.4203],
        [0.2498],
        [0.2340],
        [0.3530],
        [0.0219],
        [0.5971],
        [0.1908],
        [0.9878],
        [0.4121],
        [0.1878],
        [0.9655],
        [0.9310],
        [0.6147],
        [0.0253],
        [0.5778]])

In [172]:
g.shape

torch.Size([18, 1])

In [175]:
d = g.view(6, -1)

In [177]:
g[0][0] = 1
d

tensor([[1.0000, 0.1150, 0.5389],
        [0.4203, 0.2498, 0.2340],
        [0.3530, 0.0219, 0.5971],
        [0.1908, 0.9878, 0.4121],
        [0.1878, 0.9655, 0.9310],
        [0.6147, 0.0253, 0.5778]])

In [212]:
a = torch.randn(6, 2)
b = torch.randn(6, 2)
c = a * b
d = torch.sum(c, dim=1)

In [247]:
a = torch.randn(3, 2)
b = a.unsqueeze(dim=1)
b

tensor([[[-2.1470,  0.4693]],

        [[-0.7005, -2.2612]],

        [[-0.2056, -0.6673]]])

In [334]:
a = torch.randn(3, 4)
a

tensor([[ 2.0146,  1.1581, -0.6280,  1.2848],
        [ 0.0081, -1.2483,  0.0801,  0.6994],
        [ 1.7687, -0.8702, -0.4849,  0.2106]])

In [413]:
x = torch.randn(3, 1)
z = torch.zeros(3, 1)
g = torch.cat((x, z), dim=1)
g.requires_grad = True
# x.requires_grad = True
# z.requires_grad = True
l = torch.mean(-torch.square(g))
l.backward()

In [419]:
g[:,1:]

tensor([[0.],
        [0.],
        [0.]], grad_fn=<SliceBackward0>)

In [358]:
def t(x):
    return x ** 2 + 2
a = torch.ones(3, 2, requires_grad=True)
b = torch.zeros(3, 1)
c = torch.cat((a, b), dim=1)
z = torch.sum(t(c) - torch.zeros_like(c))
z.backward()

tensor(24., grad_fn=<SumBackward0>)

In [248]:
c = torch.randn(3, 2, 2)
c

tensor([[[-1.2056, -0.2942],
         [ 0.0869, -0.6678]],

        [[-0.8665, -0.3370],
         [-0.3098, -0.9897]],

        [[-1.2215,  1.1381],
         [ 0.5559,  2.0055]]])

In [255]:
d = torch.randn(3, 2).unsqueeze(dim=2)
e = d.expand_as(c)
e[1]

tensor([[ 2.0886,  2.0886],
        [-1.7030, -1.7030]])

In [262]:
g = torch.sum(c * e, dim=1)

tensor([[-1.1951, -0.0179],
        [-1.2823,  0.9815],
        [ 1.0219, -4.3168]])

In [282]:
kk = torch.distributions.Normal(torch.tensor([1.0]), torch.tensor([1.0]))

In [288]:
torch.normal(torch.randn(3, 5), torch.abs(torch.randn(3, 5))).shape

torch.Size([3, 5])

In [290]:
a = torch.randn(1, 2, 4)
a

tensor([[[-1.4792, -0.2155,  0.3315, -0.2551],
         [ 0.0538, -1.3072,  0.7378,  0.1132]]])

In [292]:
a.squeeze(dim=0).shape

torch.Size([2, 4])

In [271]:
torch.tensor([1, 2, 3]).unsqueeze(0).repeat(5, 1).shape

torch.Size([5, 3])

In [267]:
torch.mean(torch.log(torch.abs(g)), dim=0)

tensor([ 0.1495, -0.8602])

In [238]:
torch.cat((a, b), dim=0)

tensor([[ 0.5812, -0.7614],
        [ 0.9483,  0.3945],
        [-1.3171,  0.0244],
        [-0.7375,  0.4646],
        [ 0.9193,  0.7448],
        [-0.2335,  0.8908],
        [ 0.7415,  0.5046],
        [ 0.5779,  1.0458],
        [ 1.1320, -0.6056],
        [ 0.8067, -0.9804],
        [ 2.1514, -0.6210],
        [ 0.2589, -1.3588]])

In [235]:
f = torch.exp(d.view(3, -1))

In [236]:
f / torch.sum(f, dim=1).unsqueeze(1)

tensor([[0.2862, 0.7138],
        [0.3881, 0.6119],
        [0.9419, 0.0581]])

In [233]:
g / h

tensor([[0.2862, 0.7138],
        [0.3881, 0.6119],
        [0.9419, 0.0581]])

In [179]:
for i in range(1, 5):
    print(i)

1
2
3
4


In [199]:
mu = torch.randn((3, 1))
mu = mu.repeat(2, 1)
mu

tensor([[0.5439],
        [0.0771],
        [0.2039],
        [0.5439],
        [0.0771],
        [0.2039]])

In [201]:
mu.shape

torch.Size([6, 1])

In [206]:
c = mu.view(3, -1)
c.shape

torch.Size([3, 2])

In [88]:
a = pd.DataFrame({'a': [1, 2, 3],
     'b': [4, 5, 6]})

In [87]:
(a['b'].value_counts() / a.shape[0]).values

array([0.33333333, 0.33333333, 0.33333333])

In [89]:
a['a'] = 1
a

a  b
0  1  4
1  1  5
2  1  6

In [60]:
torch.tensor(a['a'].values)

tensor([1, 2, 3])

In [72]:
c = torch.tensor([1, 1, 1])
d = torch.tensor([2, 2, 2])
e = torch.cat((c, d), dim=0)
c[:] = 3
e
c

tensor([3, 3, 3])

In [64]:
c

2

In [38]:
x = torch.randn((3, 3))

In [41]:
x1 = x.unsqueeze(dim=1).expand_as(mu)
x1.size()

torch.Size([3, 2, 3])

tensor([[[-0.4188, -0.3362, -0.3925],
         [-0.4188, -0.3362, -0.3925]],

        [[ 1.1694,  0.1003,  0.2921],
         [ 1.1694,  0.1003,  0.2921]],

        [[-1.4250, -0.2158,  1.0102],
         [-1.4250, -0.2158,  1.0102]]])