In [51]:
import torch

import pandas as pd
import numpy as np
import torch.nn as nn

In [79]:
a = torch.randn(3, 2)
b = torch.randn(3, 2)
torch.sum(a * b, dim=1).unsqueeze(1).shape

torch.Size([3, 1])

In [298]:
pi = torch.randn(3, 2)
pi_ = torch.exp(pi)
pi_

tensor([[0.8265, 0.9079],
        [0.5721, 5.1133],
        [2.0180, 0.2811]])

In [302]:
pi_ = pi_ / torch.sum(pi_, dim=1).unsqueeze(1).expand_as(pi_)
pi_

tensor([[0.4765, 0.5235],
        [0.1006, 0.8994],
        [0.8777, 0.1223]])

In [303]:
mu = torch.randn(3, 2, 3)
sigma = torch.abs(torch.randn(3, 2, 3))

In [305]:
mix = torch.distributions.Categorical(pi_)
comp = torch.distributions.Independent(torch.distributions.Normal(mu, sigma), 1)
gmm = torch.distributions.MixtureSameFamily(mix, comp)

In [329]:
d = gmm.sample()
d

tensor([[ 0.1713, -1.5641, -0.1730],
        [-2.0129,  0.8305, -1.4073],
        [-0.1666, -0.4928,  0.3084]])

In [330]:
d.view(-1, 3)

tensor([[ 0.1713, -1.5641, -0.1730],
        [-2.0129,  0.8305, -1.4073],
        [-0.1666, -0.4928,  0.3084]])

In [109]:
a = torch.tensor([1, 2, 3, 4])
b = torch.zeros((4, 4))
torch.eye(4, 4)[1]

tensor([0., 1., 0., 0.])

In [169]:
f = torch.rand(3, 1)

In [170]:
g = f.clone().detach()
g

tensor([[0.6147],
        [0.0253],
        [0.5778]])

In [171]:

for i in range(5):
    f = torch.rand(3, 1)
    g = torch.concat((f, g), dim=0)
g


tensor([[0.1551],
        [0.1150],
        [0.5389],
        [0.4203],
        [0.2498],
        [0.2340],
        [0.3530],
        [0.0219],
        [0.5971],
        [0.1908],
        [0.9878],
        [0.4121],
        [0.1878],
        [0.9655],
        [0.9310],
        [0.6147],
        [0.0253],
        [0.5778]])

In [172]:
g.shape

torch.Size([18, 1])

In [175]:
d = g.view(6, -1)

In [177]:
g[0][0] = 1
d

tensor([[1.0000, 0.1150, 0.5389],
        [0.4203, 0.2498, 0.2340],
        [0.3530, 0.0219, 0.5971],
        [0.1908, 0.9878, 0.4121],
        [0.1878, 0.9655, 0.9310],
        [0.6147, 0.0253, 0.5778]])

In [212]:
a = torch.randn(6, 2)
b = torch.randn(6, 2)
c = a * b
d = torch.sum(c, dim=1)

In [247]:
a = torch.randn(3, 2)
b = a.unsqueeze(dim=1)
b

tensor([[[-2.1470,  0.4693]],

        [[-0.7005, -2.2612]],

        [[-0.2056, -0.6673]]])

In [334]:
a = torch.randn(3, 4)
a

tensor([[ 2.0146,  1.1581, -0.6280,  1.2848],
        [ 0.0081, -1.2483,  0.0801,  0.6994],
        [ 1.7687, -0.8702, -0.4849,  0.2106]])

In [413]:
x = torch.randn(3, 1)
z = torch.zeros(3, 1)
g = torch.cat((x, z), dim=1)
g.requires_grad = True
# x.requires_grad = True
# z.requires_grad = True
l = torch.mean(-torch.square(g))
l.backward()

In [419]:
g[:,1:]

tensor([[0.],
        [0.],
        [0.]], grad_fn=<SliceBackward0>)

In [358]:
def t(x):
    return x ** 2 + 2
a = torch.ones(3, 2, requires_grad=True)
b = torch.zeros(3, 1)
c = torch.cat((a, b), dim=1)
z = torch.sum(t(c) - torch.zeros_like(c))
z.backward()

tensor(24., grad_fn=<SumBackward0>)

In [248]:
c = torch.randn(3, 2, 2)
c

tensor([[[-1.2056, -0.2942],
         [ 0.0869, -0.6678]],

        [[-0.8665, -0.3370],
         [-0.3098, -0.9897]],

        [[-1.2215,  1.1381],
         [ 0.5559,  2.0055]]])

In [255]:
d = torch.randn(3, 2).unsqueeze(dim=2)
e = d.expand_as(c)
e[1]

tensor([[ 2.0886,  2.0886],
        [-1.7030, -1.7030]])

In [262]:
g = torch.sum(c * e, dim=1)

tensor([[-1.1951, -0.0179],
        [-1.2823,  0.9815],
        [ 1.0219, -4.3168]])

In [282]:
kk = torch.distributions.Normal(torch.tensor([1.0]), torch.tensor([1.0]))

In [288]:
torch.normal(torch.randn(3, 5), torch.abs(torch.randn(3, 5))).shape

torch.Size([3, 5])

In [290]:
a = torch.randn(1, 2, 4)
a

tensor([[[-1.4792, -0.2155,  0.3315, -0.2551],
         [ 0.0538, -1.3072,  0.7378,  0.1132]]])

In [292]:
a.squeeze(dim=0).shape

torch.Size([2, 4])

In [271]:
torch.tensor([1, 2, 3]).unsqueeze(0).repeat(5, 1).shape

torch.Size([5, 3])

In [267]:
torch.mean(torch.log(torch.abs(g)), dim=0)

tensor([ 0.1495, -0.8602])

In [238]:
torch.cat((a, b), dim=0)

tensor([[ 0.5812, -0.7614],
        [ 0.9483,  0.3945],
        [-1.3171,  0.0244],
        [-0.7375,  0.4646],
        [ 0.9193,  0.7448],
        [-0.2335,  0.8908],
        [ 0.7415,  0.5046],
        [ 0.5779,  1.0458],
        [ 1.1320, -0.6056],
        [ 0.8067, -0.9804],
        [ 2.1514, -0.6210],
        [ 0.2589, -1.3588]])

In [235]:
f = torch.exp(d.view(3, -1))

In [236]:
f / torch.sum(f, dim=1).unsqueeze(1)

tensor([[0.2862, 0.7138],
        [0.3881, 0.6119],
        [0.9419, 0.0581]])

In [233]:
g / h

tensor([[0.2862, 0.7138],
        [0.3881, 0.6119],
        [0.9419, 0.0581]])

In [179]:
for i in range(1, 5):
    print(i)

1
2
3
4


In [199]:
mu = torch.randn((3, 1))
mu = mu.repeat(2, 1)
mu

tensor([[0.5439],
        [0.0771],
        [0.2039],
        [0.5439],
        [0.0771],
        [0.2039]])

In [201]:
mu.shape

torch.Size([6, 1])

In [206]:
c = mu.view(3, -1)
c.shape

torch.Size([3, 2])

In [55]:
a = pd.DataFrame({'a': [1, 2, 3],
     'b': [4, 5, 6]})

In [62]:
a['a'] = 1
a

a  b
0  1  4
1  1  5
2  1  6

In [60]:
torch.tensor(a['a'].values)

tensor([1, 2, 3])

In [72]:
c = torch.tensor([1, 1, 1])
d = torch.tensor([2, 2, 2])
e = torch.cat((c, d), dim=0)
c[:] = 3
e
c

tensor([3, 3, 3])

In [64]:
c

2

In [38]:
x = torch.randn((3, 3))

In [41]:
x1 = x.unsqueeze(dim=1).expand_as(mu)
x1.size()

torch.Size([3, 2, 3])

tensor([[[-0.4188, -0.3362, -0.3925],
         [-0.4188, -0.3362, -0.3925]],

        [[ 1.1694,  0.1003,  0.2921],
         [ 1.1694,  0.1003,  0.2921]],

        [[-1.4250, -0.2158,  1.0102],
         [-1.4250, -0.2158,  1.0102]]])