In [1]:
import numpy as np
from exp_data import single_continuous_treatment

In [5]:
for i, j in enumerate(np.ones((5, 4))):
    print(j)

[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]


## Single continuous treatment.
Valid estimation models include
- DeepIV
- DoubleML
- CausalTree

In [2]:
train, val, treatment_effect = single_continuous_treatment()

In [6]:
np.concatenate(([1, 4], [2, 3]))

array([1, 4, 2, 3])

In [6]:
x = np.arange(0, 5).reshape(-1, 1)
y = np.arange(5, 10).reshape(-1, 1)
c = np.arange(7, 12).reshape(-1, 1)
b = np.arange(6, 11).reshape(-1, 1)
z = np.concatenate((y, b), axis=1)
x_ = np.concatenate((x, c), axis=1)

In [11]:
xy = np.vstack([x, y])

In [13]:
xy == np.concatenate((x, y), axis=0)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [ ]:
np.concatenate

In [19]:
z = np.concatenate((x, y), axis=1)

In [22]:
from functools import reduce
def cross_product(*XS):
    for X in XS:
        assert 2 >= np.ndim(X) >= 1
    n = np.shape(XS[0])[0]
    for X in XS:
        assert n == np.shape(X)[0]

    def cross(XS):
        k = len(XS)
        XS = [np.reshape(XS[i], (n,) + (1,) * (k - i - 1) + (-1,) + (1,) * i) for i in range(k)]
        return np.reshape(reduce(np.multiply, XS), (n, -1))
    return cross(XS)


In [30]:
x_

array([[ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11]])

In [31]:
z

array([[ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])

In [48]:
d = np.array([1, 2]).reshape(1, -1)
e = np.array([3, 4]).reshape(1, -1)
e

array([[3, 4]])

In [50]:
cross_product(d, e)

array([[3, 6, 4, 8]])

In [52]:
np.kron(e, d)

array([[3, 6, 4, 8]])

In [56]:
np.kron(e, np.ones(3))

array([[3., 3., 3., 4., 4., 4.]])

In [60]:
cross_product(e, np.ones(3).reshape(1, -1))

array([[3., 4., 3., 4., 3., 4.]])

In [72]:
X = np.random.normal(size=(5, 3))
y = X[:, 0] + X[:, 1] + np.random.normal(0, 0.01, size=(5,))
z = np.ones((X.shape[0], 1)) * X[:, 0].reshape(-1, 1)
z

array([[-1.66547205],
       [-0.43569922],
       [-0.98905047],
       [ 0.49403187],
       [-1.82909351]])

In [77]:
np.kron(np.ones(1), np.array([2]))

array([2.])

In [9]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6]])
y = np.array([1, 2, 3, 4, 5])
z = np.array([3, 4, 6, 7, 8])
r = np.ones(5)

In [118]:
X.shape

(5, 2)

In [30]:
a = {'a': 1,
     'b': 2}

In [31]:
a.pop('a')

1

In [32]:
a

{'b': 2}

In [26]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=2)
fold = kf.split(X)

In [24]:
list(fold)

[(array([3, 4]), array([0, 1, 2])), (array([0, 1, 2]), array([3, 4]))]

In [94]:
def _convert_str(*S):
    S = list(S)
    for i, s in enumerate(S):
        if isinstance(s, str):
            S[i] = tuple(s)
    return S

_convert_str('a', 'b', 'c')

[('a',), ('b',), ('c',)]

In [111]:
d = {
    'a': np.array([1, 2, 3]),
    'b': np.array([4, 5, 6])
}
import pandas as pd
dd = pd.DataFrame(d)
dd.keys()

Index(['a', 'b'], dtype='object')

In [116]:
def convert2array(*S):
    data = S[0]
    S = list(S[1:])

    for i, s in enumerate(S):
        S[i] = data[s].values if s is not None else None

    return S
convert2array(dd, 'a', 'b', None)


[array([1, 2, 3]), array([4, 5, 6]), None]

In [114]:
d['a']

array([1, 2, 3])