In [4]:
import numpy as np
from exp_data import single_continuous_treatment

## Single continuous treatment.
Valid estimation models include
- DeepIV
- DoubleML
- CausalTree

In [2]:
train, val, treatment_effect = single_continuous_treatment()

In [3]:
train

w_0       w_1       w_2       w_3       w_4       w_5       w_6  \
1212 -1.010090 -1.793770 -0.704964  0.083557  0.481427 -0.048769 -0.194278   
1690  0.458838  0.284358 -0.456428  1.166463 -1.124323 -0.093801  3.306066   
1198 -0.894299  0.720393  1.682601  0.215710  0.732282 -1.210671  0.305657   
401  -0.298571 -1.671269  0.260021 -1.836556  1.249896 -2.137694  0.234445   
512  -0.008337  0.312129  2.535573 -1.778272  2.412057 -2.550452  0.696291   
...        ...       ...       ...       ...       ...       ...       ...   
1323  0.473488 -0.246827 -0.829371  0.167178  2.051812 -1.098893 -2.022564   
929   0.062928  0.663101 -0.003895  0.283313  0.150168  0.676016 -0.800642   
652  -0.474054 -0.208888  0.843013  1.233498  0.275309  2.065287  0.029058   
553   0.144784 -0.631134 -0.768283  0.646175 -2.800647  0.303113  1.030039   
382  -1.012182 -2.310253  0.726641 -0.180945 -0.162788  0.318379 -1.055082   

           w_7       w_8       w_9  ...      w_23      w_24      w_25  \
1212 -0.817631  0.267509  0.388186  ...  0.174202  0.705857 -1.235907   
1690  1.980896  0.628333 -0.282192  ...  0.018890 -2.091498  0.994543   
1198 -0.427936  3.042174 -0.673378  ... -1.396297  0.527429  1.084672   
401  -1.012757 -0.203846 -0.045091  ... -0.697999 -0.147662  0.010062   
512   1.054566  1.074932 -0.494271  ...  0.436000  1.084067 -1.606550   
...        ...       ...       ...  ...       ...       ...       ...   
1323  1.115111 -0.843840  0.027017  ...  0.734411  0.659410 -0.066118   
929  -2.142750  1.956881 -0.023682  ...  0.433028  0.492842 -0.446452   
652   0.007994  1.498871  0.045821  ...  1.713916  2.251417 -0.007995   
553   0.206670  0.752679  0.937146  ...  0.985607 -1.607408  1.784038   
382   0.725277 -0.489057  0.761651  ...  0.221864  0.369722 -0.378601   

          w_26      w_27      w_28      w_29       c_0    outcome  treatment  
1212 -1.240211  0.307156 -0.250887  0.955369  0.155103  -0.391496  -0.049943  
1690  2.341314  0.946668  0.601337 -0.028910  0.335181  -0.884389  -0.495657  
1198  0.017845 -1.970667  0.183399  0.292241  0.547452   3.535996   1.082807  
401  -0.701577 -0.903222 -0.303378 -1.196278  0.477712  -5.814209  -0.726763  
512   0.782404  0.928994 -2.466212 -1.042824  0.076972   5.347627   3.144719  
...        ...       ...       ...       ...       ...        ...        ...  
1323  0.836309 -0.187636 -1.201602 -0.812195  0.887783   9.797455   1.707117  
929  -1.392282  0.161448 -0.281472  2.292087  0.540622   1.633430   0.008218  
652  -0.729207  0.872539 -1.748384 -0.784325  0.720702 -10.299303  -1.758245  
553   0.048513  0.593881  1.885963  0.295527  0.217212   0.237139  -0.660572  
382   1.938581  0.781012 -0.270042  0.760944  0.673528   1.637244   0.375009  

[1500 rows x 33 columns]

In [6]:
np.concatenate(([1, 4], [2, 3]))

array([1, 4, 2, 3])

In [7]:
[1, 4] + [2, 3]

[1, 4, 2, 3]

In [27]:
x = np.arange(0, 5).reshape(-1, 1)
y = np.arange(5, 10).reshape(-1, 1)
c = np.arange(7, 12).reshape(-1, 1)
b = np.arange(6, 11).reshape(-1, 1)
z = np.concatenate((y, b), axis=1)
x_ = np.concatenate((x, c), axis=1)

In [18]:
xy = np.hstack([x, y])

In [19]:
z = np.concatenate((x, y), axis=1)

In [22]:
from functools import reduce
def cross_product(*XS):
    for X in XS:
        assert 2 >= np.ndim(X) >= 1
    n = np.shape(XS[0])[0]
    for X in XS:
        assert n == np.shape(X)[0]

    def cross(XS):
        k = len(XS)
        XS = [np.reshape(XS[i], (n,) + (1,) * (k - i - 1) + (-1,) + (1,) * i) for i in range(k)]
        return np.reshape(reduce(np.multiply, XS), (n, -1))
    return cross(XS)


In [30]:
x_

array([[ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11]])

In [31]:
z

array([[ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])

In [48]:
d = np.array([1, 2]).reshape(1, -1)
e = np.array([3, 4]).reshape(1, -1)
e

array([[3, 4]])

In [50]:
cross_product(d, e)

array([[3, 6, 4, 8]])

In [52]:
np.kron(e, d)

array([[3, 6, 4, 8]])

In [56]:
np.kron(e, np.ones(3))

array([[3., 3., 3., 4., 4., 4.]])

In [60]:
cross_product(e, np.ones(3).reshape(1, -1))

array([[3., 4., 3., 4., 3., 4.]])

In [72]:
X = np.random.normal(size=(5, 3))
y = X[:, 0] + X[:, 1] + np.random.normal(0, 0.01, size=(5,))
z = np.ones((X.shape[0], 1)) * X[:, 0].reshape(-1, 1)
z

array([[-1.66547205],
       [-0.43569922],
       [-0.98905047],
       [ 0.49403187],
       [-1.82909351]])

In [77]:
np.kron(np.ones(1), np.array([2]))

array([2.])

In [117]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6]])
y = np.array([1, 2, 3, 4, 5])

In [118]:
X.shape

(5, 2)

In [119]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=2)
fold = kf.split(X, y)

In [120]:
list(fold)

[(array([3, 4]), array([0, 1, 2])), (array([0, 1, 2]), array([3, 4]))]

In [94]:
def _convert_str(*S):
    S = list(S)
    for i, s in enumerate(S):
        if isinstance(s, str):
            S[i] = tuple(s)
    return S

_convert_str('a', 'b', 'c')

[('a',), ('b',), ('c',)]

In [111]:
d = {
    'a': np.array([1, 2, 3]),
    'b': np.array([4, 5, 6])
}
import pandas as pd
dd = pd.DataFrame(d)
dd.keys()

Index(['a', 'b'], dtype='object')

In [116]:
def convert2array(*S):
    data = S[0]
    S = list(S[1:])

    for i, s in enumerate(S):
        S[i] = data[s].values if s is not None else None

    return S
convert2array(dd, 'a', 'b', None)


[array([1, 2, 3]), array([4, 5, 6]), None]

In [114]:
d['a']

array([1, 2, 3])